sudo: false
cache: bundler

language: ruby

rvm:
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.5.6
  - 2.5.7
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.7.0

matrix:
  fast_finish: true
  # allow_failures:
  #   - rvm: ruby-head
  #   - rvm: jruby-19mode
  #   - rvm: jruby-9.0.1.0
  #   - rvm: rbx-

before_install: 'gem install bundler'

script:
  - bundle exec rake
